name: Build Talos Extension

on:
  workflow_dispatch:
  push:
      branches:
        - master

jobs:
  BuildAndPublish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          cd extensions/cifs-utils
          docker buildx build --push --platform linux/amd64 -t ghcr.io/dias-joaovictor/cifs-utils:1.0 .

      - name: Build Talos Docker Image
        run: |
          cd extensions/cifs-utils
          
          docker run -t --rm -v "${PWD}/_out":/out \
            ghcr.io/siderolabs/imager:v1.10.5 installer \
            --system-extension-image ghcr.io/dias-joaovictor/cifs-utils:1.0
          
          docker load -i ./_out/installer-amd64.tar
          
          docker tag ghcr.io/siderolabs/installer-base:v1.10.5 ghcr.io/dias-joaovictor/cifs-utils-installer:1.0
          docker push ghcr.io/dias-joaovictor/cifs-utils-installer:1.0
#
#      - name: Push Docker Image
#        run: |
#           docker tag cars-backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/cars-backend:latest
#           docker push ${{ secrets.DOCKERHUB_USERNAME }}/cars-backend:latest
