name: Build SideroLabs Extension

on:
  workflow_dispatch:
  push:
      branches:
        - master

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2

#      - name: Build Docker Image
#        run: |
#          docker build -t cars-backend:latest .
#
#      - name: Push Docker Image
#        run: |
#           docker tag cars-backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/cars-backend:latest
#           docker push ${{ secrets.DOCKERHUB_USERNAME }}/cars-backend:latest
